---
# tasks file for bootstrap

- name: python is installed       # noqa 301
  raw: |
    if [ $(command -v apt-get) ]; then
      apt-get update \
      && apt-get install -y \
        python sudo bash ca-certificates systemd-sysv
    elif [ $(command -v dnf) ]; then
      dnf makecache \
      && dnf --assumeyes install \
        python3 python3-pip sudo python3-devel python3-dnf bash python3-libselinux \
      && dnf clean all
    elif [ $(command -v yum) ]; then
      yum makecache fast \
      && yum install -y \
        python sudo yum-plugin-ovl bash \
      && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf
    fi
  become: true
  tags: molecule-idempotence-notest
